int32 id # 指令id

int32 addr # 初始地址

int32 mx_value # 线圈的值

uint8 mw_type # 0-int32 1-uint16 2-uint32 3-float
int32 mw_int32_value # int32寄存器的值
uint16 mw_uint16_value # uint32寄存器的值
uint32 mw_uint32_value # uint32寄存器的值
float32 mw_float_value # uint32寄存器的值


---
int32 err_code # 错误码
KossiState pub_state # 科斯的状态
int32 mx_val # 单个线圈的值，与addr一起用
int32 mw_int32_val # 单个寄存器的值，与addr与mw_type一起用
uint16 mw_uint16_val # 单个寄存器的值，与addr与mw_type一起用
uint32 mw_uint32_val # 单个寄存器的值，与addr与mw_type一起用
float32 mw_float_val # 单个寄存器的值，与addr与mw_type一起用
