int32 id
string point
int32 task_id
string[] point_list
int32 do_id
bool state

float64 vx
float64 vy
float64 vw
float64 dist
float64 angle
int32 duration
int32 mode
---
int32 task_status # 导航状态
int32 task_type # 导航类型
string target_id # 导航目标站点

int32 err_code
string[] station_list
string current_station
float64 battery_level
