int8 id   # 命令id
string name # 照片名
---
int8 err_code  # 是否请求成功
ObjectInfo detected_objects #返回物体的信息列表
ObjectWidth detected_widths #返回物体的宽度列表
ObjectAperture detected_apertures #返回物体的光圈识别列表
float32 quantity
int32 speed # 转速
string name # 文件名
